# -*- coding: utf-8 -*-
"""sniff.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARIQ5XDFULGR7-XHNUVEiKzbZa5Qyylv
"""

!pip install scapy
import scapy.all as scapy

def sniff(interface):
    scapy.sniff(iface=interface, store=False, prn=process_packet)

def process_packet(packet):
    if packet.haslayer(scapy.IP):
        ip_src = packet[scapy.IP].src
        ip_dst = packet[scapy.IP].dst
        protocol = packet[scapy.IP].proto

        print(f"IP Source: {ip_src}, IP Destination: {ip_dst}, Protocol: {protocol}")

        if packet.haslayer(scapy.TCP):
            src_port = packet[scapy.TCP].sport
            dst_port = packet[scapy.TCP].dport
            print(f"TCP Source Port: {src_port}, TCP Destination Port: {dst_port}")

        elif packet.haslayer(scapy.UDP):
            src_port = packet[scapy.UDP].sport
            dst_port = packet[scapy.UDP].dport
            print(f"UDP Source Port: {src_port}, UDP Destination Port: {dst_port}")

        elif packet.haslayer(scapy.ICMP):
            icmp_type = packet[scapy.ICMP].type
            icmp_code = packet[scapy.ICMP].code
            print(f"ICMP Type: {icmp_type}, ICMP Code: {icmp_code}")

# Replace 'eth0' with your network interface (you can find it using ifconfig or ipconfig)
sniff("eth0")